//go:build linux

package gatewaylauncher

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
)

const lockName = "origin.lock"
const journalName = "origin.json"
const stagingName = "origin.next"
const maxJournalBytes = 256 * 1024
const retainedLimit = 64

var (
	ErrUnsafe    = errors.New("launcher: unsafe protected authority")
	ErrBusy      = errors.New("launcher: origin lock occupied")
	ErrBinding   = errors.New("launcher: exact binding rejected")
	ErrEvidence  = errors.New("launcher: unresolved local evidence")
	ErrStorage   = errors.New("launcher: protected durability failed")
	ErrSaturated = errors.New("launcher: retained evidence saturated")
)

// Binding is generated by the supervisor, never supplied as launch authority.
// Callers retain the complete value with their original kernel operation.
type Binding struct {
	OriginRef   string `json:"originRef"`
	BootID      string `json:"bootId"`
	PID         int    `json:"pid"`
	BirthTicks  uint64 `json:"birthTicks"`
	Incarnation string `json:"incarnation"`
	LockDevice  uint64 `json:"lockDevice"`
	LockInode   uint64 `json:"lockInode"`
}

// Receipt is local teardown evidence, not a provider or database authorization.
type Receipt struct {
	Binding Binding `json:"binding"`
	Scope   string  `json:"scope"`
	Method  string  `json:"method"`
}

const LocalTeardownScope = "exact-local-process-transport-teardown-v1"

type record struct {
	Binding Binding `json:"binding"`
	Phase   string  `json:"phase"`
}

type journal struct {
	Version  int       `json:"version"`
	Current  record    `json:"current"`
	Receipts []Receipt `json:"receipts"`
}

type authority struct {
	dir     *os.File
	lock    *os.File
	dirPath string
	device  uint64
	inode   uint64
}

func randomID() (string, error) {
	var b [32]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", ErrStorage
	}
	return hex.EncodeToString(b[:]), nil
}

func statFD(f *os.File) (syscall.Stat_t, error) {
	var s syscall.Stat_t
	err := syscall.Fstat(int(f.Fd()), &s)
	return s, err
}

func validFile(s syscall.Stat_t) bool {
	return s.Uid == 0 && s.Mode&syscall.S_IFMT == syscall.S_IFREG && s.Mode&0777 == 0600 && s.Nlink == 1
}

// Walk every directory component using a pinned descriptor and O_NOFOLLOW.
// Production paths cannot traverse a writable ancestor, even a sticky /tmp.
func openAuthority(path string) (*authority, error) {
	if os.Geteuid() != 0 || !filepath.IsAbs(path) || filepath.Clean(path) != path || path == "/" {
		return nil, ErrUnsafe
	}
	fd, err := syscall.Open("/", syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_CLOEXEC|syscall.O_NOFOLLOW, 0)
	if err != nil {
		return nil, ErrUnsafe
	}
	d := os.NewFile(uintptr(fd), "protected-directory")
	prefix := ""
	for _, part := range strings.Split(strings.TrimPrefix(path, "/"), "/") {
		prefix += "/" + part
		next, e := syscall.Openat(int(d.Fd()), part, syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_CLOEXEC|syscall.O_NOFOLLOW, 0)
		if e != nil {
			d.Close()
			return nil, ErrUnsafe
		}
		d.Close()
		d = os.NewFile(uintptr(next), "protected-directory")
		s, e := statFD(d)
		if e != nil || s.Uid != 0 || s.Mode&syscall.S_IFMT != syscall.S_IFDIR || s.Mode&0022 != 0 || (prefix == path && s.Mode&0777 != 0700) {
			d.Close()
			return nil, ErrUnsafe
		}
	}
	a := &authority{dir: d, dirPath: path}
	return a, nil
}

func (a *authority) openFile(name string, flags int) (*os.File, error) {
	fd, err := syscall.Openat(int(a.dir.Fd()), name, flags|syscall.O_NOFOLLOW|syscall.O_CLOEXEC|syscall.O_NONBLOCK, 0600)
	if err != nil {
		return nil, ErrUnsafe
	}
	f := os.NewFile(uintptr(fd), "protected-record")
	s, err := statFD(f)
	if err != nil || !validFile(s) {
		f.Close()
		return nil, ErrUnsafe
	}
	return f, nil
}

func (a *authority) checkDirectory() error {
	b, err := openAuthority(a.dirPath)
	if err != nil {
		return err
	}
	defer b.dir.Close()
	s, err := statFD(a.dir)
	t, e := statFD(b.dir)
	if err != nil || e != nil || s.Dev != t.Dev || s.Ino != t.Ino {
		return ErrUnsafe
	}
	return nil
}

func (a *authority) checkLock() error {
	if err := a.checkDirectory(); err != nil {
		return err
	}
	f, err := a.openFile(lockName, syscall.O_RDWR)
	if err != nil {
		return err
	}
	defer f.Close()
	s, err := statFD(f)
	if err != nil || uint64(s.Dev) != a.device || s.Ino != a.inode {
		return ErrBinding
	}
	return nil
}

func (a *authority) acquire(create bool) error {
	// Linux local flock supports read-only descriptors. The inherited FD
	// cannot write or truncate the root-owned lock inode.
	flags := syscall.O_RDONLY
	if create {
		flags |= syscall.O_CREAT
	}
	f, err := a.openFile(lockName, flags)
	if err != nil {
		return err
	}
	if err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		f.Close()
		if err == syscall.EWOULDBLOCK || err == syscall.EAGAIN {
			return ErrBusy
		}
		return ErrUnsafe
	}
	s, err := statFD(f)
	if err != nil {
		f.Close()
		return ErrUnsafe
	}
	a.lock = f
	a.device, a.inode = uint64(s.Dev), s.Ino
	if err = a.checkLock(); err != nil {
		f.Close()
		a.lock = nil
		return err
	}
	// Persist creation without ever modifying the inode's contents.
	if err = f.Sync(); err == nil {
		err = a.dir.Sync()
	}
	if err != nil {
		a.lock.Close()
		a.lock = nil
		return ErrStorage
	}
	return nil
}

func (a *authority) close() {
	// Closing our reference is safe: the child's inherited reference shares
	// this open description. NEVER call LOCK_UN, truncate or unlink the lock.
	if a.lock != nil {
		a.lock.Close()
		a.lock = nil
	}
	if a.dir != nil {
		a.dir.Close()
		a.dir = nil
	}
}

func (a *authority) read() (journal, bool, error) {
	var j journal
	fd, err := syscall.Openat(int(a.dir.Fd()), journalName, syscall.O_RDONLY|syscall.O_CLOEXEC|syscall.O_NOFOLLOW|syscall.O_NONBLOCK, 0)
	if err == syscall.ENOENT {
		return j, false, nil
	}
	if err != nil {
		return j, false, ErrUnsafe
	}
	f := os.NewFile(uintptr(fd), "protected-record")
	defer f.Close()
	s, err := statFD(f)
	if err != nil || !validFile(s) || s.Size > maxJournalBytes {
		return j, false, ErrUnsafe
	}
	dec := json.NewDecoder(io.LimitReader(f, maxJournalBytes+1))
	dec.DisallowUnknownFields()
	if err = dec.Decode(&j); err != nil {
		return j, false, ErrEvidence
	}
	var extra any
	if dec.Decode(&extra) != io.EOF || j.Version != 1 || len(j.Receipts) > retainedLimit {
		return j, false, ErrEvidence
	}
	// These records are emitted only by this supervisor. Requiring its exact
	// encoding rejects duplicate/case-aliased fields and other corrupt bytes.
	if _, err = f.Seek(0, io.SeekStart); err != nil {
		return j, false, ErrEvidence
	}
	raw, err := io.ReadAll(io.LimitReader(f, maxJournalBytes+1))
	canonical, e := json.Marshal(j)
	if err != nil || e != nil || !bytes.Equal(raw, canonical) {
		return j, false, ErrEvidence
	}
	// Visible replacement bytes after a failed fsync are not yet durable
	// proof. Re-establish durability before returning retained facts.
	if f.Sync() != nil || a.dir.Sync() != nil {
		return j, false, ErrStorage
	}
	return j, true, nil
}

func (a *authority) write(j journal) error {
	if a.lock == nil {
		return ErrEvidence
	}
	if err := a.checkLock(); err != nil {
		return err
	}
	data, err := json.Marshal(j)
	if err != nil || len(data) > maxJournalBytes {
		return ErrStorage
	}
	// One exclusive staging slot bounds even crash-abandoned records. If a
	// supervisor died with the slot present, preserve it and deny publication;
	// never discard an unresolved record to make room for another incarnation.
	name := stagingName
	f, err := a.openFile(name, syscall.O_WRONLY|syscall.O_CREAT|syscall.O_EXCL)
	if err != nil {
		return err
	}
	defer syscall.Unlinkat(int(a.dir.Fd()), name)
	_, err = f.Write(data)
	if err == nil {
		err = f.Sync()
	}
	ce := f.Close()
	if err == nil {
		err = ce
	}
	if err != nil {
		return ErrStorage
	}
	if err = a.checkLock(); err != nil {
		return err
	}
	if err = syscall.Renameat(int(a.dir.Fd()), name, int(a.dir.Fd()), journalName); err != nil {
		return ErrStorage
	}
	if err = a.dir.Sync(); err != nil {
		return ErrStorage
	}
	return nil
}

func bootID() (string, error) {
	b, err := os.ReadFile("/proc/sys/kernel/random/boot_id")
	s := strings.TrimSpace(string(b))
	if err != nil || len(s) != 36 {
		return "", ErrEvidence
	}
	return s, nil
}

// /proc stat's parenthesized comm can contain spaces and parentheses.
func birth(pid int) (uint64, byte, error) {
	b, err := os.ReadFile("/proc/" + strconv.Itoa(pid) + "/stat")
	if err != nil {
		return 0, 0, err
	}
	end := strings.LastIndexByte(string(b), ')')
	if end < 0 {
		return 0, 0, ErrEvidence
	}
	f := strings.Fields(string(b[end+1:]))
	if len(f) < 20 || len(f[0]) != 1 {
		return 0, 0, ErrEvidence
	}
	n, err := strconv.ParseUint(f[19], 10, 64)
	if err != nil || n == 0 {
		return 0, 0, ErrEvidence
	}
	return n, f[0][0], nil
}

func fullBinding(b Binding) bool {
	if b.PID <= 0 || b.BirthTicks == 0 || b.LockInode == 0 || len(b.BootID) != 36 || len(b.Incarnation) != 64 || b.OriginRef == "" {
		return false
	}
	_, err := hex.DecodeString(b.Incarnation)
	return err == nil
}

func (a *authority) validate(j journal, origin, boot string) error {
	base := j.Current.Binding
	if base.OriginRef != origin || base.BootID != boot || base.LockDevice != a.device || base.LockInode != a.inode || len(base.Incarnation) != 64 {
		return ErrBinding
	}
	if _, err := hex.DecodeString(base.Incarnation); err != nil {
		return ErrBinding
	}
	seen := map[string]bool{}
	for _, r := range j.Receipts {
		b := r.Binding
		if !fullBinding(b) || b.OriginRef != origin || b.BootID != boot || b.LockDevice != a.device || b.LockInode != a.inode || r.Scope != LocalTeardownScope || (r.Method != "observed-child-exit" && r.Method != "reacquired-after-supervisor-loss") || seen[b.Incarnation] {
			return ErrBinding
		}
		seen[b.Incarnation] = true
	}
	switch j.Current.Phase {
	case "starting", "ready":
		if !fullBinding(base) || seen[base.Incarnation] {
			return ErrEvidence
		}
	case "retired":
		if !fullBinding(base) {
			return ErrEvidence
		}
		found := false
		for _, r := range j.Receipts {
			if r.Binding == base {
				found = true
			}
		}
		if !found {
			return ErrEvidence
		}
	case "reserved", "start-failed":
		if base.PID != 0 || base.BirthTicks != 0 || seen[base.Incarnation] {
			return ErrEvidence
		}
	default:
		return ErrEvidence
	}
	return nil
}

func (a *authority) recover(j *journal) error {
	switch j.Current.Phase {
	case "retired", "start-failed":
		return nil
	case "reserved":
		return ErrEvidence // crash window lacks exact birth identity
	}
	b := j.Current.Binding
	// A reused PID is an explicit denial. Neither a fresh boot nor the absence
	// of a busy local boolean is evidence. Reacquired flock AND protected exact
	// metadata AND absent original PID or exact kernel-reported terminated
	// birth are required. A zombie may remain until its unrelated parent reaps.
	n, state, err := birth(b.PID)
	absent := errors.Is(err, os.ErrNotExist)
	exactExited := err == nil && n == b.BirthTicks && (state == 'Z' || state == 'X')
	if !absent && !exactExited {
		return ErrBinding
	}
	if len(j.Receipts) >= retainedLimit {
		return ErrSaturated
	}
	j.Receipts = append(j.Receipts, Receipt{b, LocalTeardownScope, "reacquired-after-supervisor-loss"})
	j.Current.Phase = "retired"
	return a.write(*j)
}
